### ISSUE TITLE
не надо держать в открытом виде в коде креды. они должны быть в env-файлах

### ISSUE THREAD

**Issue by nazarov-nikolay** [Miks-Muks/cube#1]
https://github.com/Miks-Muks/cube/blob/7e9318ed9a345e33b49c18afd653d4d7145a5d36/shop/services.py#L8

**Comment by Miks-Muks** [comment]
да знаю изменил.

**Comment by nazarov-nikolay** [comment]
А как изменил? не нахожу что-то. Если в .env перенес, то в репу надо добавить .env.examle с названиями переменных без значений. И в ридми это указать в инструкции по разворачиванию.
